spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/store_api?createDatabaseIfNotExist=true
    username: root
    password: 7539
  jpa:
    show-sql: true
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: ${ACTOKEXP}
    refreshTokenExpiration : ${RETOKEXP}

stripe:
    secretKey: ${STRIPE_SECRET_KEY}
    publicKey: ${STRIPE_PUBLIC_KEY}

websiteUrl: http://localhost:3000